# @format

BOT:
  OWNERS: ["948937171031695411"]
  ADMINS: [""]

LINKS:
  SUPPORT: "https://dsc.gg/discronix"
  MONGO_URI: "mongodb+srv://Securebot:X8MxCyPNBFt8U9Yu@cluster0.g6pwm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

SPOTIFY:
  ID: "e6f84fbec2b44a77bf35a20c5ffa54b8"
  SECRET: "98f461b962443cfaf9539c610e2ea81"

MANAGER:
  OWNER: "948937171031695411"
  TOKEN: ""

FUEGO:
  PREFIX: "1"
  EMOJIS: "black"
  COLOR: "#07f7fa"
  SHARDS: 1
  PER_CLUSTER: 1
  TOKEN: ""
  TOPGGAUTH: "https://top.gg/bot/1215354057246511104/vote"


WEBHOOKS:
  ERROR: ""
  STATIC: ""
  PLAYER: ""
  SERVER: ""
  COMMAND: ""
